#!/usr/bin/env bash

###
### These are specific to the test harness
###
CANOPUS_SUBSYSTEM_MAP='CANOPUS_STATISTICS_MAP_SUBSYSTEM'
CANOPUS_OVERALL_MAP='CANOPUS_STATISTICS_MAP_OVERALL'
CANOPUS_TEST_SUBSYSTEM=
CANOPUS_TEST_PREVIOUS_SUBSYSTEM=

exported_vars="CANOPUS_SUBSYSTEM_MAP CANOPUS_OVERALL_MAP CANOPUS_TEST_SUBSYSTEM CANOPUS_TEST_PREVIOUS_SUBSYSTEM"

__import_all_variables "${exported_vars}"
